apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvault-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudvault
  template:
    metadata:
      labels:
        app: cloudvault
    spec:
      containers:
      - name: cloudvault
        image: cloudvaultacr.azurecr.io/cloudvault:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: cloudvault-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: cloudvault-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: cloudvault
